import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Marquee from "@/components/marquee";
import { Suspense } from "react";
import Footer from "@/components/footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div className="mx-auto h-28 w-full max-w-7xl animate-pulse bg-white" />}>
          <Header />
        </Suspense>
        <Suspense fallback={<div className="h-10 bg-white-700" />}>
          <Marquee />
        </Suspense>
        <main className="max-w-7xl mx-auto">
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  );
}
